[project]
name = "summary-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.14",
    "gigachat>=0.1.40",
    "newspaper3k>=0.2.8",
    "requests>=2.32.4",
]
